safe: true
markdown: kramdown
highlighter: pygments
permalink: /:title.html
relative_permalinks: false

default_theme: varya
default_width: 792
default_lang: en
default_body_class: shower list

author:
    name: Varya Stepanova
    url:  http://varya.me
    company:
        name: Wonna
        url:  https://wonna.fi

fork_url: https://github.com/varya/component-development-css-2019
progress: true
line_numbers: true
